export const links=[
 {href:'/',label:'Home'},
 {href:'/Movies',label:'Movies'},
 {href:'/MostPopular',label:'Most Popular'},
 {href:'/Anime',label:'Anime'},
 {href:'/Manga',label:'Manga'},
]
export const animeList=[
 {id:1,
  title:'Jujutsu Kaisen 2nd Season',
  link:'https://hianime.to/watch/jujutsu-kaisen-2nd-season-18413?ep=102662',
  EpCount:'23',
  subEpCount:'23',
  dubEpCount:'23',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/b51f863b05f30576cf9d85fa9b911bb5.png',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'The year is 2006, and the halls of Tokyo Prefectural Jujutsu High School echo with the endless bickering and intense debate between two inseparable best friends. Exuding unshakeable confidence, Satoru Gojou and Suguru Getou believe there is no challenge too great for young and powerful Special Grade sorcerers such as themselves. They are tasked with safely delivering a sensible girl named Riko Amanai to the entity whose existence is the very essence of the jujutsu world. However, the mission plunges them into an exhausting swirl of moral conflict that threatens to destroy the already feeble amity between sorcerers and ordinary humans. Twelve years later, students and sorcerers are the frontline defense against the rising number of high-level curses born from humans negative emotions. As the entities grow in power, their self-awareness and ambition increase too. The curses unite for the common goal of eradicating humans and creating a world of only cursed energy users, led by a dangerous, ancient cursed spirit. To dispose of their greatest obstacle—the strongest sorcerer, Gojou—they orchestrate an attack at Shibuya Station on Halloween. Dividing into teams, the sorcerers enter the fight prepared to risk everything to protect the innocent and their own kind.',
  searches:1020,
 },
 {id:2,
  title:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc',
  link:'https://hianime.to/watch/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100090',
  EpCount:'11',
  subEpCount:'11',
  dubEpCount:'11',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/db2f3ce7b9cab7fdc160b005bffb899a.png',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'It adapts the story from volume 12 (chapter 98 onwards) of the manga series "Demon Slayer: Kimetsu no Yaiba" . The story takes place in a new setting - Tanjiro arrives at the "Swordsmith Village." After the death of Upper Moon Six and Daki, a vacancy appears among the upper moons, and Muzan Kibutsuji summons the remaining upper moons to the Infinity Castle. Muzan is furious about the vacancy and believes that the upper moons should do everything in their power to find the "Blue Spider Lily" and eliminate the Demon Slayer Corps. As a result, Upper Moon Four, Hantengu, and Upper Moon Five, Gyokko, are dispatched to carry out the mission. Meanwhile, Tanjiro, who has been recovering from his injuries at the Butterfly Estate for two months, learns that Kozo Kanamori, the swordsmith, has refused to make him a new sword. Following the advice of the Hashira, Shinobu Kocho, Suma Nakahara, and Kiyo Terauchi, Tanjiro travels to the Swordsmith Village to conUpon arrival, he encounters the Love Hashira, Mitsuri Kanroji, and the Mist Hashira, Muichiro Tokito, as well as Genya Shinazugawa. Tanjiro and his companions are about to embark on a new battle. The opening theme song "Ketsui no Hikari" is performed by MAN WITH A MISSION and milet. The lyrics and composition are by Jean-Ken Johnny, with arrangement by MAN WITH A MISSION and cooperation by Chisato Ichinose. The ending theme song "Koikogare" is also performed by MAN WITH A MISSION and milet.',
  searches:1390,
 },
 {id:3,
  title:'Spy x Family',
  link:'https://hianime.to/watch/spy-x-family-17977?ep=89506',
  EpCount:'36',
  subEpCount:'36',
  dubEpCount:'36',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/88bd17534dc4884f23027035d23d74e5.jpg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:false,
  PGrating:'pg-13',
  quality:'hd',
  description:"For the agent known as 'Twilight', no order is too tall if it is for the sake of peace. Operating as Westalis master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician Donovan Desmond by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family. Twilight, or 'Loid Forger', quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin 'Thorn Princess'. For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun. Under the guise of 'The Forgers', the spy, the assassin, and the esper must act as a family while carrying out their own agendas. Although these liars and misfits are only playing parts, they soon find that family is about far more than blood relations.",
  searches:890,
 },
 {id:4,
  title:'Jujutsu Kaisen 2nd Season',
  link:'https://hianime.to/watch/jujutsu-kaisen-2nd-season-18413?ep=102662',
  EpCount:'23',
  subEpCount:'23',
  dubEpCount:'23',
  image:'/sukuna.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'The year is 2006, and the halls of Tokyo Prefectural Jujutsu High School echo with the endless bickering and intense debate between two inseparable best friends. Exuding unshakeable confidence, Satoru Gojou and Suguru Getou believe there is no challenge too great for young and powerful Special Grade sorcerers such as themselves. They are tasked with safely delivering a sensible girl named Riko Amanai to the entity whose existence is the very essence of the jujutsu world. However, the mission plunges them into an exhausting swirl of moral conflict that threatens to destroy the already feeble amity between sorcerers and ordinary humans. Twelve years later, students and sorcerers are the frontline defense against the rising number of high-level curses born from humans negative emotions. As the entities grow in power, their self-awareness and ambition increase too. The curses unite for the common goal of eradicating humans and creating a world of only cursed energy users, led by a dangerous, ancient cursed spirit. To dispose of their greatest obstacle—the strongest sorcerer, Gojou—they orchestrate an attack at Shibuya Station on Halloween. Dividing into teams, the sorcerers enter the fight prepared to risk everything to protect the innocent and their own kind.',
  searches:778,
 },
 {id:5,
  title:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc',
  link:'https://hianime.to/watch/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100090',
  EpCount:'11',
  subEpCount:'11',
  dubEpCount:'11',
  image:'/tanjiro.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'It adapts the story from volume 12 (chapter 98 onwards) of the manga series "Demon Slayer: Kimetsu no Yaiba" . The story takes place in a new setting - Tanjiro arrives at the "Swordsmith Village." After the death of Upper Moon Six and Daki, a vacancy appears among the upper moons, and Muzan Kibutsuji summons the remaining upper moons to the Infinity Castle. Muzan is furious about the vacancy and believes that the upper moons should do everything in their power to find the "Blue Spider Lily" and eliminate the Demon Slayer Corps. As a result, Upper Moon Four, Hantengu, and Upper Moon Five, Gyokko, are dispatched to carry out the mission. Meanwhile, Tanjiro, who has been recovering from his injuries at the Butterfly Estate for two months, learns that Kozo Kanamori, the swordsmith, has refused to make him a new sword. Following the advice of the Hashira, Shinobu Kocho, Suma Nakahara, and Kiyo Terauchi, Tanjiro travels to the Swordsmith Village to conUpon arrival, he encounters the Love Hashira, Mitsuri Kanroji, and the Mist Hashira, Muichiro Tokito, as well as Genya Shinazugawa. Tanjiro and his companions are about to embark on a new battle. The opening theme song "Ketsui no Hikari" is performed by MAN WITH A MISSION and milet. The lyrics and composition are by Jean-Ken Johnny, with arrangement by MAN WITH A MISSION and cooperation by Chisato Ichinose. The ending theme song "Koikogare" is also performed by MAN WITH A MISSION and milet.',
  searches:798,

 },
 {id:6,
  title:'Spy x Family',
  link:'https://hianime.to/watch/spy-x-family-17977?ep=89506',
  EpCount:'36',
  subEpCount:'36',
  dubEpCount:'36',
  image:'/yorforger.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:false,
  PGrating:'pg-13',
  quality:'hd',
  description:"For the agent known as 'Twilight', no order is too tall if it is for the sake of peace. Operating as Westalis master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician Donovan Desmond by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family. Twilight, or 'Loid Forger', quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin 'Thorn Princess'. For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun. Under the guise of 'The Forgers', the spy, the assassin, and the esper must act as a family while carrying out their own agendas. Although these liars and misfits are only playing parts, they soon find that family is about far more than blood relations.",
  searches:1108,
 },
 {id:1,
  title:'Jujutsu Kaisen 2nd Season',
  link:'https://hianime.to/watch/jujutsu-kaisen-2nd-season-18413?ep=102662',
  EpCount:'23',
  subEpCount:'23',
  dubEpCount:'23',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/b51f863b05f30576cf9d85fa9b911bb5.png',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'The year is 2006, and the halls of Tokyo Prefectural Jujutsu High School echo with the endless bickering and intense debate between two inseparable best friends. Exuding unshakeable confidence, Satoru Gojou and Suguru Getou believe there is no challenge too great for young and powerful Special Grade sorcerers such as themselves. They are tasked with safely delivering a sensible girl named Riko Amanai to the entity whose existence is the very essence of the jujutsu world. However, the mission plunges them into an exhausting swirl of moral conflict that threatens to destroy the already feeble amity between sorcerers and ordinary humans. Twelve years later, students and sorcerers are the frontline defense against the rising number of high-level curses born from humans negative emotions. As the entities grow in power, their self-awareness and ambition increase too. The curses unite for the common goal of eradicating humans and creating a world of only cursed energy users, led by a dangerous, ancient cursed spirit. To dispose of their greatest obstacle—the strongest sorcerer, Gojou—they orchestrate an attack at Shibuya Station on Halloween. Dividing into teams, the sorcerers enter the fight prepared to risk everything to protect the innocent and their own kind.',
  searches:1020,
 },
 {id:2,
  title:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc',
  link:'https://hianime.to/watch/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100090',
  EpCount:'11',
  subEpCount:'11',
  dubEpCount:'11',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/db2f3ce7b9cab7fdc160b005bffb899a.png',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'It adapts the story from volume 12 (chapter 98 onwards) of the manga series "Demon Slayer: Kimetsu no Yaiba" . The story takes place in a new setting - Tanjiro arrives at the "Swordsmith Village." After the death of Upper Moon Six and Daki, a vacancy appears among the upper moons, and Muzan Kibutsuji summons the remaining upper moons to the Infinity Castle. Muzan is furious about the vacancy and believes that the upper moons should do everything in their power to find the "Blue Spider Lily" and eliminate the Demon Slayer Corps. As a result, Upper Moon Four, Hantengu, and Upper Moon Five, Gyokko, are dispatched to carry out the mission. Meanwhile, Tanjiro, who has been recovering from his injuries at the Butterfly Estate for two months, learns that Kozo Kanamori, the swordsmith, has refused to make him a new sword. Following the advice of the Hashira, Shinobu Kocho, Suma Nakahara, and Kiyo Terauchi, Tanjiro travels to the Swordsmith Village to conUpon arrival, he encounters the Love Hashira, Mitsuri Kanroji, and the Mist Hashira, Muichiro Tokito, as well as Genya Shinazugawa. Tanjiro and his companions are about to embark on a new battle. The opening theme song "Ketsui no Hikari" is performed by MAN WITH A MISSION and milet. The lyrics and composition are by Jean-Ken Johnny, with arrangement by MAN WITH A MISSION and cooperation by Chisato Ichinose. The ending theme song "Koikogare" is also performed by MAN WITH A MISSION and milet.',
  searches:1390,
 },
 {id:3,
  title:'Spy x Family',
  link:'https://hianime.to/watch/spy-x-family-17977?ep=89506',
  EpCount:'36',
  subEpCount:'36',
  dubEpCount:'36',
  image:'https://cdn.noitatnemucod.net/thumbnail/300x400/100/88bd17534dc4884f23027035d23d74e5.jpg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:false,
  PGrating:'pg-13',
  quality:'hd',
  description:"For the agent known as 'Twilight', no order is too tall if it is for the sake of peace. Operating as Westalis master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician Donovan Desmond by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family. Twilight, or 'Loid Forger', quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin 'Thorn Princess'. For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun. Under the guise of 'The Forgers', the spy, the assassin, and the esper must act as a family while carrying out their own agendas. Although these liars and misfits are only playing parts, they soon find that family is about far more than blood relations.",
  searches:890,
 },
 {id:4,
  title:'Jujutsu Kaisen 2nd Season',
  link:'https://hianime.to/watch/jujutsu-kaisen-2nd-season-18413?ep=102662',
  EpCount:'23',
  subEpCount:'23',
  dubEpCount:'23',
  image:'/sukuna.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'The year is 2006, and the halls of Tokyo Prefectural Jujutsu High School echo with the endless bickering and intense debate between two inseparable best friends. Exuding unshakeable confidence, Satoru Gojou and Suguru Getou believe there is no challenge too great for young and powerful Special Grade sorcerers such as themselves. They are tasked with safely delivering a sensible girl named Riko Amanai to the entity whose existence is the very essence of the jujutsu world. However, the mission plunges them into an exhausting swirl of moral conflict that threatens to destroy the already feeble amity between sorcerers and ordinary humans. Twelve years later, students and sorcerers are the frontline defense against the rising number of high-level curses born from humans negative emotions. As the entities grow in power, their self-awareness and ambition increase too. The curses unite for the common goal of eradicating humans and creating a world of only cursed energy users, led by a dangerous, ancient cursed spirit. To dispose of their greatest obstacle—the strongest sorcerer, Gojou—they orchestrate an attack at Shibuya Station on Halloween. Dividing into teams, the sorcerers enter the fight prepared to risk everything to protect the innocent and their own kind.',
  searches:778,
 },
 {id:5,
  title:'Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc',
  link:'https://hianime.to/watch/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100090',
  EpCount:'11',
  subEpCount:'11',
  dubEpCount:'11',
  image:'/tanjiro.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:true,
  PGrating:'r',
  quality:'hd',
  description:'It adapts the story from volume 12 (chapter 98 onwards) of the manga series "Demon Slayer: Kimetsu no Yaiba" . The story takes place in a new setting - Tanjiro arrives at the "Swordsmith Village." After the death of Upper Moon Six and Daki, a vacancy appears among the upper moons, and Muzan Kibutsuji summons the remaining upper moons to the Infinity Castle. Muzan is furious about the vacancy and believes that the upper moons should do everything in their power to find the "Blue Spider Lily" and eliminate the Demon Slayer Corps. As a result, Upper Moon Four, Hantengu, and Upper Moon Five, Gyokko, are dispatched to carry out the mission. Meanwhile, Tanjiro, who has been recovering from his injuries at the Butterfly Estate for two months, learns that Kozo Kanamori, the swordsmith, has refused to make him a new sword. Following the advice of the Hashira, Shinobu Kocho, Suma Nakahara, and Kiyo Terauchi, Tanjiro travels to the Swordsmith Village to conUpon arrival, he encounters the Love Hashira, Mitsuri Kanroji, and the Mist Hashira, Muichiro Tokito, as well as Genya Shinazugawa. Tanjiro and his companions are about to embark on a new battle. The opening theme song "Ketsui no Hikari" is performed by MAN WITH A MISSION and milet. The lyrics and composition are by Jean-Ken Johnny, with arrangement by MAN WITH A MISSION and cooperation by Chisato Ichinose. The ending theme song "Koikogare" is also performed by MAN WITH A MISSION and milet.',
  searches:798,

 },
 {id:6,
  title:'Spy x Family',
  link:'https://hianime.to/watch/spy-x-family-17977?ep=89506',
  EpCount:'36',
  subEpCount:'36',
  dubEpCount:'36',
  image:'/yorforger.jpeg',
  EpDuration:'24',
  sub:true,
  dub:true,
  isAdult:false,
  PGrating:'pg-13',
  quality:'hd',
  description:"For the agent known as 'Twilight', no order is too tall if it is for the sake of peace. Operating as Westalis master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician Donovan Desmond by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family. Twilight, or 'Loid Forger', quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin 'Thorn Princess'. For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun. Under the guise of 'The Forgers', the spy, the assassin, and the esper must act as a family while carrying out their own agendas. Although these liars and misfits are only playing parts, they soon find that family is about far more than blood relations.",
  searches:1108,
 },
]